Dump start stop
Concordium/concordium-java-sdk pull request #227
Opened 2023-04-20 12:06 UTC by magnusbechwind

## Purpose

Implements dumpStart and dumpStop

## Changes

Implemented the above methods

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2023-04-21 08:43 UTC, EmilLa1 requested changes
Looks good!

A few nitpicky things and it's good to go.

2023-04-21 08:43 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java
> +     * @throws {@link io.grpc.StatusRuntimeException} if the network dump failed to start
... Or if the node was not build with the feature right?

2023-04-21 08:43 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/requests/dumpstart/DumpRequest.java
> +     * Whether the node should dump raw packages
```suggestion
     * Whether the node should dump raw packages.
```

2023-04-21 08:43 UTC, EmilLa1 commented on CHANGELOG.md
> +- Added support for GRPC V2 Dump Start
```suggestion
- Added support for GRPC V2 `DumpStart` which instructs the node to start dumping network packages at a specified path.
```

2023-04-21 08:43 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/requests/dumpstart/DumpRequest.java
> +    private final File file;
I think a `Path` would be the better option here, as the SDK retains no handle to the file that is specified.

2023-04-27 17:46 UTC, abizjak approved these changes

2023-05-08 11:49 UTC, EmilLa1 approved these changes

2023-05-08 12:20 UTC, merged