Acceptable request
Concordium/concordium-java-sdk pull request #327
Opened 2024-03-13 11:49 UTC by shjortConcordium

## Purpose

Add bindings for acceptable request / statement from concordium-base wallet_library.

## Changes

_Describe the changes that were needed.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2024-03-13 12:20 UTC, orhoj requested changes

2024-03-13 12:20 UTC, orhoj commented on concordium-sdk/src/main/java/com/concordium/sdk/crypto/CryptoJniNative.java
> +     * @return JSON representing {@link StringResult}. If successful the field 'result' is empty,
You are kind of abusing `StringResult` if this is what you are doing. You could make a type specifically for this.

2024-03-13 12:20 UTC, orhoj commented on concordium-sdk/src/main/java/com/concordium/sdk/crypto/CryptoJniNative.java
> +    public static native String isAcceptableAtomicStatement(String input, String rangeTags, String setTags, AcceptableRequest.RawAttributeCheck check);
Missing javadoc.

2024-03-13 12:20 UTC, orhoj commented on crypto-jni/src/lib.rs
> +/// The JNI wrapper for checking that a request is acceptable.
The docs here are the same as for the other method.

2024-03-13 12:20 UTC, orhoj commented on crypto-jni/src/lib.rs
> +    let request: AtomicStatement<constants::ArCurve, String, Web3IdAttribute> =
Not a request, rename the variable.

2024-03-13 12:20 UTC, orhoj commented on crypto-jni/src/lib.rs
> +    request_input: JString,
statement_input

2024-03-14 12:58 UTC, shjortConcordium commented on concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/AcceptableRequest.java
> +     * Check that a request is acceptable
I've tried to expand on it.

2024-03-14 12:59 UTC, shjortConcordium commented on concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/AcceptableRequest.java
> +     * @return a Presentation serialized as JSON
I've changed it to use a specific exception instead. :thinking:

2024-03-18 08:13 UTC, orhoj approved these changes

2024-03-18 08:46 UTC, merged