Query : PeerTotalSent
Concordium/concordium-java-sdk pull request #76
Opened 2022-08-10 20:43 UTC by parv0888

## Purpose
Adds support for query `PeerTotalSent`

## Changes
Adds support for query `PeerTotalSent`

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2022-08-12 06:42 UTC, EmilLa1 requested changes
Looks good. :+1: 

Minor comments. 

Can you add it to the appropriate section of the README.md also?
Here
https://github.com/Concordium/concordium-java-sdk/blob/main/README.md#fill-in
and here
https://github.com/Concordium/concordium-java-sdk/blob/main/README.md#fill-in-1

2022-08-12 06:42 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * Gets the total No of sent packets.
```suggestion
     * Gets the total number of packets sent.
```

2022-08-12 06:42 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * @return Total no of Sent Packets.
```suggestion
     * @return Total number of packets sent.
```

2022-08-15 06:30 UTC, parv0888 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * Gets the total No of sent packets.
done

2022-08-15 06:30 UTC, parv0888 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * @return Total no of Sent Packets.
done

2022-08-15 07:46 UTC, EmilLa1 approved these changes
Looks good. 👍 
Please rebase so we can get it merged.

2022-08-17 06:33 UTC, merged