Query : PeerVersion
Concordium/concordium-java-sdk pull request #77
Opened 2022-08-10 21:00 UTC by parv0888

## Purpose
Adds support for `PeerVersion`

## Changes
Adds support for `PeerVersion`

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2022-08-15 07:43 UTC, EmilLa1 requested changes
While I empathize with the decision of adding the `Semver`  package.  Unfortunately  currently it does not look like it is properly maintained, see e.g.:  https://github.com/vdurmont/semver4j/issues/57

I suggest we just store the node version in a `String` for now.

2022-08-17 20:45 UTC, parv0888 commented
> 
Sure @EmilLa1  - Rust SDK was using a a similar approach to return a parsed semantic version. 
Thanks. Its done

2022-08-18 03:58 UTC, abizjak commented
> > 
> 
> Sure @EmilLa1 - Rust SDK was using a a similar approach to return a parsed semantic version. Thanks. Its done

I think the point is that the dependency was not maintained, not that we should not be parsing the response.

The Rust SDK uses the canonical ecosystem semver parsing library that is used, among others, but the compiler toolchain itself.

2022-08-18 04:53 UTC, parv0888 commented
> > > 
> > 
> > 
> > Sure @EmilLa1 - Rust SDK was using a a similar approach to return a parsed semantic version. Thanks. Its done
> 
> I think the point is that the dependency was not maintained, not that we should not be parsing the response.
> 
> The Rust SDK uses the canonical ecosystem semver parsing library that is used, among others, but the compiler toolchain itself.

@EmilLa1 , @abizjak  - Can you please suggest a library. I will use that.

2022-08-18 08:51 UTC, EmilLa1 commented
Looks like there is a maintained fork semver4j. 

https://github.com/semver4j/semver4j

I would suggest going with that.

2022-08-18 10:54 UTC, parv0888 commented
> @parv0888 Looks like there is a maintained semver4j fork .
> 
> https://github.com/semver4j/semver4j
> 
> I would suggest going with that.

Thanks @EmilLa1 
its been done

2022-08-18 12:39 UTC, EmilLa1 commented on README.md
> +String version = client.getVersion();
```suggestion
SemVer version = client.getVersion();
```

2022-08-18 12:39 UTC, EmilLa1 commented on README.md
> +String getVersion()
```suggestion
SemVer getVersion()
```

2022-08-18 13:15 UTC, parv0888 commented on README.md
> +String version = client.getVersion();
done

2022-08-18 13:15 UTC, parv0888 commented on README.md
> +String getVersion()
done

2022-08-19 07:29 UTC, EmilLa1 approved these changes

2022-08-19 07:30 UTC, EmilLa1 commented
Please rebase and we can merge it.

2022-08-19 12:22 UTC, parv0888 commented
> Please rebase and we can merge it.

thanks, done

2022-08-22 07:23 UTC, merged