Get ancestors
Concordium/concordium-java-sdk pull request #82
Opened 2022-08-18 13:10 UTC by parv0888

## Purpose

_Describe the purpose of the pull request, link to issue describing the problem, etc.

## Changes

_Describe the changes that were needed.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

2022-08-27 19:59 UTC, EmilLa1 requested changes
Looks generally good, I don't think the `BlockAncestors` type brings much value to the table right now, so I suggest that we simply return `ImmutableList<Hash>`.

2022-08-27 19:59 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +    public BlockAncestors getAncestors(Hash blockHash, long num) throws BlockNotFoundException {
I think this should just return `ImmutableList<Hash>`.

2022-08-27 19:59 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/responses/getancestors/BlockAncestors.java
> +public class BlockAncestors {
I don't think this abstraction provides much functionality, so I propose to simply delete it and return `ImmutableList<Hash>`.

2022-08-27 19:59 UTC, EmilLa1 commented on README.md
> +Gets Ancestor Blocks for the provided input Block Hash.
```suggestion
Get a list of block hashes that preceding the provided block hash and with a maximum size of the provided number.
```

2022-08-29 08:42 UTC, EmilLa1 requested changes
Even it's a simple query, I urge you to add a unit test for parsing the returned JSON.
To do that you probably want to factor out the deserialization logic into a separate helper function. 

Otherwise looks good.

2022-08-29 16:49 UTC, parv0888 commented
> Even it's a simple query, I urge you to add a unit test for parsing the returned JSON. To do that you probably want to factor out the deserialization logic into a separate helper function.
> 
> Otherwise looks good.

Thanks, Added unit tests

2022-08-31 07:37 UTC, EmilLa1 approved these changes
Looks good

2022-08-31 07:37 UTC, merged