Query : Get Instances
Concordium/concordium-java-sdk pull request #86
Opened 2022-08-19 13:30 UTC by parv0888

## Purpose
Added support for `GetInstances`

## Changes
Added support for `GetInstances`

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2022-08-27 20:18 UTC, EmilLa1 requested changes
Looks good.
Please provide a unit test.

2022-08-27 20:18 UTC, EmilLa1 commented on README.md
> +Get the list of smart contract instances in a given block.
```suggestion
Get a list of all smart contract instances that exist in the state at the end of the given block.
```

2022-08-27 20:18 UTC, EmilLa1 commented on README.md
> +val contractInstances = client
Please provide type.

2022-08-27 20:18 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * Get the list of smart contract instances in a given block.
This is not entirely correct. 
The list returned will contain all instances that exists at the end of the given block. 

So something like "Get a list of all smart contract instances that exist in the state at the end of the given block." will better describe it.

2022-08-30 16:26 UTC, parv0888 commented on README.md
> +val contractInstances = client
done

2022-09-19 08:00 UTC, EmilLa1 approved these changes
Looks good

2022-09-19 08:01 UTC, merged