Query : Start & Stop Baker
Concordium/concordium-java-sdk pull request #99
Opened 2022-08-26 09:14 UTC by parv0888

## Purpose

- Added support for query `StartBaker`
- Added support for query `StopBaker`

## Changes

- Added support for query `StartBaker`
- Added support for query `StopBaker`

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2022-08-27 22:10 UTC, EmilLa1 requested changes

2022-08-27 22:10 UTC, EmilLa1 commented on README.md
> +Start the baker in the consensus module.
```suggestion
Start the baker.
```

2022-08-27 22:10 UTC, EmilLa1 commented on README.md
> +Stop the baker in the consensus module.
```suggestion
Stop the baker.
```

2022-08-27 22:10 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * Start the baker in the consensus module.
```suggestion
     * Start the baker.
```

2022-08-27 22:10 UTC, EmilLa1 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * Stop the baker in the consensus module.
```suggestion
     * Stop the baker.
```

2022-09-22 13:03 UTC, parv0888 commented on README.md
> +Start the baker in the consensus module.
done

2022-09-22 13:04 UTC, parv0888 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * Start the baker in the consensus module.
done

2022-09-22 13:04 UTC, parv0888 commented on concordium-sdk/src/main/java/com/concordium/sdk/Client.java
> +     * Stop the baker in the consensus module.
done

2022-09-23 09:40 UTC, EmilLa1 approved these changes

2022-09-23 09:41 UTC, merged